apiVersion: v1
kind: Service
metadata:
  name: deloitte-app
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: deloitte-app
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
